### ISSUE TITLE
Not working well in sidebars.

### ISSUE THREAD

**Issue by Manrunas** [OfficerHalf/obsidian-auto-class#34]
AutoClass does not work well if I drag note to sidebar. Initially my custom class is added and custom CSS style works, but when I load a workspace or restart Obsidian, my custom class is missing if note is in a sidebar as a tab (checked with DevTools).

**Comment by OfficerHalf** [comment]
What version of Obsidian are you on?

**Comment by Manrunas** [comment]
version 0.14.15

**Comment by Manrunas** [comment]
Found another occurrence of this issue. I open the note which has a tag linked to custom style. All is fine, custom style applied. Then I open same note multiple times, and each time in new pane. All is fine again and custom style is applied to all panes. However, when I restart the Obsidian, the custom stylesheet is applied to the last active pane only. I have to manually go throught panes and quickly toggle Edit/Reading mode, then the custom style activates as it should.

**Comment by OfficerHalf** [comment]
Hmm, I expect these are two separate issues; I'll do some investigation and figure it out.

1. My expectation is that the plugin won't work at all for sidebar panes. The fact that it does at first is probably coincidental. This is probably something that could be supported though. If it's not a bug and is working as intended, then we can make this an enhancement.
2. Are the panes linked? I added handling for this but it's been a minute since I tested it. Very possible something in the internal API changed and broke it.

**Comment by Manrunas** [comment]
I did a recording of my screen, both issues, the link is below:
https://screenrec.com/share/Hhe83f5oyS

1. Having a possibility to style a pane located inside a sidebar would be very very handy. For example I intend to use it for cheatsheets of shortcuts or anything else. Left and Right sidebars are accessible with single keystroke on in my setup from my mouse. By default there is no possibility to target particular pane in a sidebar with custom CSS snippet. Unfortunately with Auto Class it resets after app restart or workspace change in Obsidian.
2. No, panes are not linked.

**Comment by Manrunas** [comment]
Looks like I solved my problem. Turns out the solution was simpler than I could imagine. No plugins are necessary. Just had to insert single YAML line :
---
cssclass: myCustomClassName
---

**Comment by OfficerHalf** [comment]
Correct, the idea of this plugin is to apply classes automatically based on path instead of having to specify the class in yaml.
